apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sender-release
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/sender
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1