namespace: event-triangle-dev
replicaCount: 1
secretKeyRef: "auth-secrets"
GrpcChannelAddresses: "http://sender-release-service.event-triangle-dev.svc.cluster.local"
image:
  # repository: kaminome/auth-service
  repository: acrsharedd01.azurecr.io/auth-service
  tag: "1.0.1-PullRequest162.7-ab3ac42"
  pullPolicy: Always
ports:
  - containerPort: 80
service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
