apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: auth-config
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/wwwroot/assets/config/config.json
              subPath: config.json
          ports:
          {{- range .Values.ports }}
            - containerPort: {{ .containerPort }}
          {{- end }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Kubernetes
            - name: REVERSEPROXY__CLUSTERS__CLUSTER1__DESTINATIONS__DESTINATION1__ADDRESS
              value: "http://sender-release-service.event-triangle-dev.svc.cluster.local"
            - name: REVERSEPROXY__CLUSTERS__CLUSTER2__DESTINATIONS__DESTINATION1__ADDRESS
              value: "http://consumer-release-service.event-triangle-dev.svc.cluster.local"
            - name: GrpcChannelAddresses
              value: {{ .Values.GrpcChannelAddresses }}
            - name: EVENT_TRIANGLE_AD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretKeyRef }}
                  key: EVENT_TRIANGLE_AD_CLIENT_SECRET
            - name: DatabaseConnectionString
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretKeyRef }}
                  key: AuthDatabaseConnectionString
            - name: RedisPassword
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretKeyRef }}
                  key: RedisPassword
            - name: RedisUrl
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretKeyRef }}
                  key: RedisUrl
