apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range .Values.ports }}
            - containerPort: {{ .containerPort }}
          {{- end }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Docker"
            - name: GrpcChannelAddresses
              value: "http://sender-release.event-triangle-dev.svc.cluster.local:81"
            - name: EVENT_TRIANGLE_AD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretKeyRef }}
                  key: EVENT_TRIANGLE_AD_CLIENT_SECRET
            - name: DatabaseConnectionString
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretKeyRef }}
                  key: AuthDatabaseConnectionString
            - name: RedisPassword
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretKeyRef }}
                  key: RedisPassword
            - name: RedisUrl
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretKeyRef }}
                  key: RedisUrl
