apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range .Values.service.ports }}
            - containerPort: {{ .targetPort }}
          {{- end }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Kubernetes
            - name: CLUSTERS__CLUSTER1__DESTINATIONS__DESTINATION1__ADDRESS
              value: "http://sender-release.event-triangle-dev.svc.cluster.local"
            - name: CLUSTERS__CLUSTER2__DESTINATIONS__DESTINATION1__ADDRESS
              value: "http://consumer-release.event-triangle-dev.svc.cluster.local"
            - name: RabbitMqHost
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretKeyRef }}
                  key: RabbitMqHost
            - name: RabbitMqUsername
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretKeyRef }}
                  key: RabbitMqUsername
            - name: RabbitMqPassword
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretKeyRef }}
                  key: RabbitMqPassword
            - name: DatabaseConnectionString
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretKeyRef }}
                  key: SenderDatabaseConnectionString
