replicaCount: 1
namespace: event-triangle-dev
secretKeyRef: "sender-secrets"
image:
  # repository: kaminome/sender-service
  repository: acrsharedd01.azurecr.io/sender-service
  tag: latest
  pullPolicy: Always
service:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
