replicaCount: 1
namespace: event-triangle-dev
secretKeyRef: "sender-secrets"
image:
  # repository: kaminome/sender-service
  repository: acrsharedd01.azurecr.io/sender-service
  tag: 1.0.1-PullRequest162.5-dbbf664
  pullPolicy: Always
service:
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: grpc
      port: 81
      targetPort: 81
  type: ClusterIP
