namespace: event-triangle-dev
replicaCount: 1

image:
  # repository: kaminome/consumer-service
  repository: acrsharedd01.azurecr.io/consumer-service
  tag: latest
  pullPolicy: Always

secretKeyRef: "consumer-secrets"

ports:
  containerPort: 80
  servicePort: 80
  targetPort: 8080
